volumes:
  elsahoot-mongodb-volume:
  elsahoot-redis-volume:

networks:
  elsahoot-network:

services:

  mongodb:
    container_name: elsahoot-mongodb
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - elsahoot-mongodb-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_AUTHN_DATABASE}
    networks:
      - elsahoot-network

  redis:
    container_name: elsahoot-redis
    image: redis:7.2.3
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - elsahoot-redis-volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    networks:
      - elsahoot-network
