"""0_init_db

Revision ID: e6e55d066bed
Revises: 
Create Date: 2024-10-26 13:31:33.029819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e55d066bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('total_score', sa.BigInteger(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riddle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('answer_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('player',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=True),
    sa.Column('riddles_pass', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_modified_on', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('quiz_riddle_association',
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('riddle_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['riddle_id'], ['riddle.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'riddle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_riddle_association')
    op.drop_table('player')
    op.drop_table('riddle')
    op.drop_table('quiz')
    # ### end Alembic commands ###
